-- scripts/seed-demo-data.sql
--
-- DEMO / LOCAL-ONLY SEED DATA. NOT FOR PRODUCTION.
--
-- Purpose: populate a freshly-created dev/Codespaces database with a
-- handful of realistic-looking short links and a plausible spread of click
-- analytics, purely so a local or Codespaces demo instance has something to
-- look at (dashboard, stats pages, top-links leaderboard) instead of being
-- empty. Every row this script inserts is clearly synthetic:
--
--   * The short links point at real, well-known public pages (github.com,
--     wikipedia.org, docs.python.org, ...) so the demo "looks real" visually,
--     but the short codes, click counts, referrers, countries and device
--     types below are all generated by this script, not by real visitors.
--   * This does NOT simulate, impersonate, or claim to represent actual
--     production traffic or real end users. There is no production
--     deployment of this project serving real users today.
--
-- Why SQL instead of a Go program: the repo's only DB access path is the
-- generated Prisma client (`backend/internal/db`), which is gitignored and
-- only exists after running `prisma generate` inside Docker/a machine with
-- network access to Prisma's engine download. A plain SQL script has no such
-- dependency, runs with nothing more than `psql`, and is trivial to read
-- line-by-line against `backend/prisma/schema.prisma` before trusting it
-- against your own database. The trade-off: it bypasses application-level
-- invariants the Go code enforces (e.g. custom-alias format, URL validation)
-- — acceptable here because this is fixed, hand-reviewed demo content, not
-- user input.
--
-- Safety / idempotency:
--   * This script checks whether its own demo short codes already exist and
--     exits without doing anything if so — safe to run more than once.
--   * It never touches `users`, existing `links`, or existing `click_events`
--     rows belonging to anyone else; it only INSERTs its own rows.
--   * It bumps the `links`/`click_events` id sequences past whatever it
--     inserts, so IDs minted afterwards by the running application (Postgres
--     SERIAL on those tables — see backend/internal/db/prisma_store.go
--     CreateLink) never collide with these rows.
--   * All seeded links use `user_id = NULL` (anonymous links), which is a
--     normal, already-supported state in this app (see
--     backend/internal/handlers/shorten.go) — no fake user accounts,
--     passwords, or API keys are created.
--   * Seeded short codes (e.g. `gh-mirror`, `wiki-ref`) are custom-alias
--     style strings containing `-`, which the app's own counter-based code
--     generator (base62: `0-9a-zA-Z` only, see
--     backend/internal/shortcode/base62.go) can never produce — so they
--     cannot collide with organically-created short codes either.
--
-- Usage (examples):
--   Local Docker Compose:
--     docker compose exec -T postgres \
--       psql -U urlshortener -d urlshortener < scripts/seed-demo-data.sql
--
--   Any reachable Postgres (e.g. inside a Codespace):
--     psql "$DATABASE_URL" -f scripts/seed-demo-data.sql
--
-- This script assumes the schema already exists (i.e. the `migrate` service
-- / `prisma db push` has run first) and is NOT part of docker-compose.yml or
-- any CI/deploy workflow — it must be run by hand, on purpose, against a
-- dev/demo database only.

DO $$
DECLARE
  existing_count int;
BEGIN
  SELECT count(*) INTO existing_count
  FROM links
  WHERE short_code IN (
    'gh-mirror', 'wiki-ref', 'py-docs', 'hn-feed',
    'nyt-world', 'so-faq', 'reddit-aww', 'mdn-js'
  );

  IF existing_count > 0 THEN
    RAISE NOTICE 'seed-demo-data: % of the demo short codes already exist — skipping, nothing inserted.', existing_count;
    RETURN;
  END IF;

  -- ---------------------------------------------------------------------
  -- Demo links: real public URLs, varied creation dates over the last
  -- ~30 days, all anonymous (user_id NULL), no expiry, no password.
  -- ---------------------------------------------------------------------
  INSERT INTO links
    (short_code, long_url, user_id, custom_alias, expires_at, password_hash, created_at)
  VALUES
    ('gh-mirror',  'https://github.com/torvalds/linux',                                  NULL, true, NULL, NULL, now() - interval '28 days'),
    ('wiki-ref',   'https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol',           NULL, true, NULL, NULL, now() - interval '25 days'),
    ('py-docs',    'https://docs.python.org/3/',                                         NULL, true, NULL, NULL, now() - interval '21 days'),
    ('hn-feed',    'https://news.ycombinator.com/',                                      NULL, true, NULL, NULL, now() - interval '18 days'),
    ('nyt-world',  'https://www.nytimes.com/section/world',                              NULL, true, NULL, NULL, now() - interval '14 days'),
    ('so-faq',     'https://stackoverflow.com/questions',                                NULL, true, NULL, NULL, now() - interval '10 days'),
    ('reddit-aww', 'https://www.reddit.com/r/aww/',                                      NULL, true, NULL, NULL, now() - interval '6 days'),
    ('mdn-js',     'https://developer.mozilla.org/en-US/docs/Web/JavaScript',            NULL, true, NULL, NULL, now() - interval '2 days');

  -- Keep the links.id SERIAL sequence ahead of what we just inserted, so the
  -- next organically-created link (via the running API) never collides.
  PERFORM setval(pg_get_serial_sequence('links', 'id'), (SELECT max(id) FROM links));

  -- ---------------------------------------------------------------------
  -- Demo click events: one row per simulated click, spread across the days
  -- each link has existed. Not a flat distribution:
  --   * each link has its own base "popularity" (some links are just
  --     busier than others, as in real analytics)
  --   * weekends run ~45% quieter than weekdays
  --   * ~12% of days get a random 2-3x "spike" (e.g. a link getting shared
  --     somewhere), the rest have normal day-to-day jitter
  -- Referrer/device/country are picked from small realistic pools.
  -- ---------------------------------------------------------------------
  INSERT INTO click_events (link_id, "timestamp", referrer, country, device_type, ip_hash)
  SELECT
    l.id,
    gs.day_start
      + (random() * interval '23 hours')
      + (random() * interval '59 minutes')
      + (random() * interval '59 seconds'),
    CASE floor(random() * 6)::int
      WHEN 0 THEN NULL                       -- direct / no referrer
      WHEN 1 THEN 'https://www.google.com/'
      WHEN 2 THEN 'https://www.google.com/'
      WHEN 3 THEN 'https://twitter.com/'
      WHEN 4 THEN 'https://x.com/'
      ELSE 'https://github.com/'
    END AS referrer,
    (ARRAY['US','IN','GB','DE','BR','CA','AU','FR','JP','NG','ES','NL'])
      [1 + floor(random() * 12)::int] AS country,
    CASE
      WHEN random() < 0.55 THEN 'desktop'
      WHEN random() < 0.85 THEN 'mobile'
      ELSE 'tablet'
    END AS device_type,
    NULL AS ip_hash  -- no real IP was ever observed for seed data; left NULL rather than faked
  FROM links l
  CROSS JOIN LATERAL (
    -- one row per day the link has existed, most-recent-first
    SELECT generate_series(0, (current_date - l.created_at::date))::int AS day_offset
  ) AS day_offsets
  CROSS JOIN LATERAL (
    SELECT (current_date - (day_offsets.day_offset * interval '1 day'))::date::timestamp AS day_start
  ) AS gs
  CROSS JOIN LATERAL (
    -- how many clicks this link gets on this particular day
    SELECT generate_series(1, GREATEST(0, round(
      (CASE l.short_code
         WHEN 'gh-mirror'   THEN 28
         WHEN 'wiki-ref'    THEN 18
         WHEN 'py-docs'     THEN 14
         WHEN 'hn-feed'     THEN 22
         WHEN 'nyt-world'   THEN 10
         WHEN 'so-faq'      THEN 16
         WHEN 'reddit-aww'  THEN 20
         WHEN 'mdn-js'      THEN 12
         ELSE 8
       END)
      * (CASE WHEN extract(dow FROM gs.day_start) IN (0, 6) THEN 0.55 ELSE 1.0 END) -- quieter weekends
      * (CASE WHEN random() < 0.12 THEN 2.0 + random() ELSE 1.0 END)                -- occasional spike day
      * (0.5 + random())                                                            -- normal day-to-day jitter
    ))::int) AS n
  ) AS clicks_today
  WHERE l.short_code IN (
    'gh-mirror', 'wiki-ref', 'py-docs', 'hn-feed',
    'nyt-world', 'so-faq', 'reddit-aww', 'mdn-js'
  );

  PERFORM setval(pg_get_serial_sequence('click_events', 'id'), (SELECT max(id) FROM click_events));

  RAISE NOTICE 'seed-demo-data: inserted % demo links and % demo click events.',
    (SELECT count(*) FROM links WHERE short_code IN (
      'gh-mirror', 'wiki-ref', 'py-docs', 'hn-feed',
      'nyt-world', 'so-faq', 'reddit-aww', 'mdn-js'
    )),
    (SELECT count(*) FROM click_events WHERE link_id IN (
      SELECT id FROM links WHERE short_code IN (
        'gh-mirror', 'wiki-ref', 'py-docs', 'hn-feed',
        'nyt-world', 'so-faq', 'reddit-aww', 'mdn-js'
      )
    ));
END $$;
